sudo: required

services:
  - docker

before_install:
  - curl -sSL https://raw.githubusercontent.com/citac/citac/$TRAVIS_BRANCH/install/install.sh | sudo bash

script:
  - var/test/travis-tests.sh

notifications:
  email: false

